<a href="https://colab.research.google.com/github/Bo-kyoung/AI-practices/blob/main/Wikidocs_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
class Calculator:
  def __init__(self):
    self.result=0
    print("선언완료")
  def add(self, num):
    self.result += num
    return self.result
cal1= Calculator()
cal2= Calculator()
print(cal1.add(3))
print(cal1.add(4))

선언완료
선언완료
3
7


In [59]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)
x_train = torch.FloatTensor([1,2,3]).unsqueeze(1)
y_train = torch.FloatTensor([2,4,6]).unsqueeze(1)

W = torch.zeros(1, requires_grad=True) # X*W이므로 (1*1)
b = torch.zeros(1, requires_grad=True) 

nb_epochs = 2999
for epoch in range(nb_epochs + 1):
  hypothesis = x_train.mul(W)+b 


  cost = torch.mean((hypothesis - y_train)**2)


  optimizer = optim.SGD([W,b], lr = 0.01)
  optimizer.zero_grad()
  cost.backward() #기울기 연산(hypothesis에 초기 w, b대입, 계산, cost에 hypothesis 대입, 계산, 해서 w, b(required step TRUE 설정) return 
  optimizer.step() #learnin late 계산 해서 기울기를 빼줌

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.4f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))



Epoch   0/2999 W: 0.1867, b: 0.080 Cost: 18.666666
Epoch 100/2999 W: 1.7457, b: 0.578 Cost: 0.048171
Epoch 200/2999 W: 1.8001, b: 0.454 Cost: 0.029767
Epoch 300/2999 W: 1.8429, b: 0.357 Cost: 0.018394
Epoch 400/2999 W: 1.8765, b: 0.281 Cost: 0.011366
Epoch 500/2999 W: 1.9029, b: 0.221 Cost: 0.007024
Epoch 600/2999 W: 1.9237, b: 0.174 Cost: 0.004340
Epoch 700/2999 W: 1.9400, b: 0.136 Cost: 0.002682
Epoch 800/2999 W: 1.9528, b: 0.107 Cost: 0.001657
Epoch 900/2999 W: 1.9629, b: 0.084 Cost: 0.001024
Epoch 1000/2999 W: 1.9709, b: 0.066 Cost: 0.000633
Epoch 1100/2999 W: 1.9771, b: 0.052 Cost: 0.000391
Epoch 1200/2999 W: 1.9820, b: 0.041 Cost: 0.000242
Epoch 1300/2999 W: 1.9858, b: 0.032 Cost: 0.000149
Epoch 1400/2999 W: 1.9889, b: 0.025 Cost: 0.000092
Epoch 1500/2999 W: 1.9913, b: 0.020 Cost: 0.000057
Epoch 1600/2999 W: 1.9931, b: 0.016 Cost: 0.000035
Epoch 1700/2999 W: 1.9946, b: 0.012 Cost: 0.000022
Epoch 1800/2999 W: 1.9958, b: 0.010 Cost: 0.000013
Epoch 1900/2999 W: 1.9967, b: 0.008 Cost

In [61]:
w = torch.tensor(2.0, requires_grad  = True)
y = w**2
z = 2*y + 5
z.backward()
print(w.grad) #미분한 수식: f(x) = 4w, w값은 2였으니 기울기는 8 

tensor(8.)


In [62]:
torch.manual_seed(1)
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) #feature가 3개(x의 개수 - dim이 3)

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [66]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

W = torch.zeros((3,1), requires_grad = True )
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W,b], lr = 1e-5)
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  hypothesis = x_train.matmul(W) + b
  cost = torch.mean((hypothesis - y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
          epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
      ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [74]:
#nn.module
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)
x_train = torch.FloatTensor([1,2,3]).unsqueeze(1)
y_train = torch.FloatTensor([2,4,6]).unsqueeze(1)
print(x_train)

model = nn.Linear(1,1)
#print(list(model.parameters()))

optimizer = torch.optim.SGD(model.parameters(), lr=0.01 )
nb_epochs = 2000

for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
     print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

tensor([[1.],
        [2.],
        [3.]])
Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [78]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)
print(list(model.parameters()))

tensor([[7.9989]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [82]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3,1) #3개의 feature 하나의 y
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 29938.339844
Epoch  100/2000 Cost: 1.459696
Epoch  200/2000 Cost: 1.404118
Epoch  300/2000 Cost: 1.351442
Epoch  400/2000 Cost: 1.301445
Epoch  500/2000 Cost: 1.254035
Epoch  600/2000 Cost: 1.209076
Epoch  700/2000 Cost: 1.166424
Epoch  800/2000 Cost: 1.125966
Epoch  900/2000 Cost: 1.087573
Epoch 1000/2000 Cost: 1.051147
Epoch 1100/2000 Cost: 1.016586
Epoch 1200/2000 Cost: 0.983798
Epoch 1300/2000 Cost: 0.952660
Epoch 1400/2000 Cost: 0.923131
Epoch 1500/2000 Cost: 0.895094
Epoch 1600/2000 Cost: 0.868473
Epoch 1700/2000 Cost: 0.843199
Epoch 1800/2000 Cost: 0.819206
Epoch 1900/2000 Cost: 0.796417
Epoch 2000/2000 Cost: 0.774786


In [84]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)
  
  def forward(self,x):
    return self.linear(x)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
model = LinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 32.361588
Epoch  100/2000 Cost: 0.012030
Epoch  200/2000 Cost: 0.007434
Epoch  300/2000 Cost: 0.004593
Epoch  400/2000 Cost: 0.002839
Epoch  500/2000 Cost: 0.001754
Epoch  600/2000 Cost: 0.001084
Epoch  700/2000 Cost: 0.000670
Epoch  800/2000 Cost: 0.000414
Epoch  900/2000 Cost: 0.000256
Epoch 1000/2000 Cost: 0.000158
Epoch 1100/2000 Cost: 0.000098
Epoch 1200/2000 Cost: 0.000060
Epoch 1300/2000 Cost: 0.000037
Epoch 1400/2000 Cost: 0.000023
Epoch 1500/2000 Cost: 0.000014
Epoch 1600/2000 Cost: 0.000009
Epoch 1700/2000 Cost: 0.000005
Epoch 1800/2000 Cost: 0.000003
Epoch 1900/2000 Cost: 0.000002
Epoch 2000/2000 Cost: 0.000001


In [93]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 
nb_epochs = 2000
for epoch in range(nb_epochs +1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 25809.587891
Epoch  100/2000 Cost: 0.298808
Epoch  200/2000 Cost: 0.292559
Epoch  300/2000 Cost: 0.286632
Epoch  400/2000 Cost: 0.281008
Epoch  500/2000 Cost: 0.275684
Epoch  600/2000 Cost: 0.270632
Epoch  700/2000 Cost: 0.265832
Epoch  800/2000 Cost: 0.261289
Epoch  900/2000 Cost: 0.256981
Epoch 1000/2000 Cost: 0.252894
Epoch 1100/2000 Cost: 0.249015
Epoch 1200/2000 Cost: 0.245331
Epoch 1300/2000 Cost: 0.241845
Epoch 1400/2000 Cost: 0.238542
Epoch 1500/2000 Cost: 0.235392
Epoch 1600/2000 Cost: 0.232420
Epoch 1700/2000 Cost: 0.229590
Epoch 1800/2000 Cost: 0.226897
Epoch 1900/2000 Cost: 0.224347
Epoch 2000/2000 Cost: 0.221932
