In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
#items= ['TV','냉장고','전자레인지','선풍기','선풍기'] 레이블 인코딩 해보기, 
item = ['TV','냉장고','전자레인지','선풍기','선풍기']
encoder = LabelEncoder()
encoder.fit(item)
result = encoder.transform(item)

In [5]:
#문자열 값이 어떤 숫자로 encoding되었는지 확인하기, 이걸로 1번은 무엇인지 확인
encoder.classes_[1]

'냉장고'

In [8]:
#원핫 인코딩을 적용하기 위한 두가지 조건: 1) 문자열이 숫자로, 2) 2차원 데이터 필요
from sklearn.preprocessing import OneHotEncoder
import numpy as np
item = ['TV','냉장고','전자레인지','선풍기','선풍기']
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(item)
labels = labels.reshape(-1,1) #axis = 1이 1로 코딩 cloumn vector형태
print(labels)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_result = oh_encoder.transform(labels)
print(oh_result.toarray())

[[0]
 [1]
 [3]
 [2]
 [2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [12]:
#회기 기반 ML은 레이블 인코딩이 가능하다 (O, X) : X!
#트리기반 ML은 레이블 인코딩이 가능하다(O,X) : O!
#판다스 기반 원핫 인코딩 함수는? get_dummies
import pandas as pd
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','선풍기','선풍기']})
pd.get_dummies(df)

item_TV  item_냉장고  item_선풍기  item_전자레인지
0        1         0         0           0
1        0         1         0           0
2        0         0         0           1
3        0         0         1           0
4        0         0         1           0