In [10]:
import numpy as np

In [6]:
sequence_array = np.arange(8.0,10)
print(sequence_array,sequence_array.dtype)

[8. 9.] float64


In [14]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d)
array2d = array3d.reshape(1,-1)
print(array2d.tolist())

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0, 1, 2, 3, 4, 5, 6, 7]]


In [4]:
array1d = np.arange(9)
array2d = array1d.reshape(3,3)
print(array2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
boolean = np.array([[False,False,False],[True,False,True],[True,True,True]])
array2d[boolean].shape

(5,)

In [42]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [43]:
sort_indices_desc = np.argsort(org_array)[::-1]

In [44]:
print(sort_indices_desc)

[2 3 0 1]


In [46]:
transpose_mat = np.transpose(array2d)
print(transpose_mat)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [93]:
import pandas as pd
titanic_df = pd.read_csv(r'C:\Users\user\PerfectGuide\train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [2]:
titanic_df.shape
titanic_df.info()
titanic_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [18]:
import numpy as np
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('arra1 shape:',array1.shape)
#리스트를 이용해 dataframe 생성
df_list1 = pd.DataFrame(list1,columns = col_name1)
print('1차원 리스트로 만든 dataframe:\n',df_list1)
#넘파이 ndarray를 이용해 dataframe 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 리스트로 만든 dataframe:\n',df_array1)

arra1 shape: (3,)
1차원 리스트로 만든 dataframe:
    col1
0     1
1     2
2     3
1차원 리스트로 만든 dataframe:
    col1
0     1
1     2
2     3


In [8]:
diction = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(diction)
print(df_dict)
df_ndarray = df_dict.values
print(df_ndarray)
print(type(df_ndarray))

   col1  col2  col3
0     1     2     3
1    11    22    33
[[ 1  2  3]
 [11 22 33]]
<class 'numpy.ndarray'>


In [64]:
#1-3 문항
array1 = np.arange(6)
array2 = array1.reshape(2,-1)
list1 = array2.tolist()
print('리스트\n',list1)
print(type(list1))
print(array2)
column = ['col1','col2','col3']
dp_array = pd.DataFrame(array2, columns = column)
print(dp_array)
print(dp_array.values)
data_dp = pd.DataFrame(list1, index = ['one','two'], columns = column)#데이터 영역에 df말고 array나 리스트
print(data_dp)
data_dp
#help(pd.DataFrame)

리스트
 [[0, 1, 2], [3, 4, 5]]
<class 'list'>
[[0 1 2]
 [3 4 5]]
   col1  col2  col3
0     0     1     2
1     3     4     5
[[0 1 2]
 [3 4 5]]
     col1  col2  col3
one     0     1     2
two     3     4     5


col1  col2  col3
one     0     1     2
two     3     4     5

In [74]:
#4번 문항
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3) #column을 여러개 지정할 때는 list형태로 넣어줘야함
titanic_df.loc[titanic_df['Age']>60,['Pclass','Age']].head(3)

Pclass   Age
33       2  66.0
54       1  65.0
96       1  71.0

In [29]:
indexes = titanic_df.index
print(indexes.values[-4:-1])

[887 888 889]


In [37]:
titanic_df['age0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  age0  
0      0         A/5 21171   7.2500   NaN        S     0  
1      0          PC 17599  71.2833   C85        C     0  
2      0  STON/O2. 3101282   7.9250   NaN        S     0

In [38]:
titanic_df.drop('age0',axis = 1, inplace=True)
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [36]:
a = titanic_df['Pclass'].value_counts()
print(a.index)
b = a.reset_index(inplace=False, drop=True)
print(b)

Int64Index([3, 1, 2], dtype='int64')
0    491
1    216
2    184
Name: Pclass, dtype: int64


In [53]:
titanic_df.iloc[1:3,0:2].index

RangeIndex(start=1, stop=3, step=1)

In [54]:
titanic_df[titanic_df['Age']>60][['Name']].head(3)

Name
33           Wheadon, Mr. Edward H
54  Ostby, Mr. Engelhart Cornelius
96       Goldschmidt, Mr. George B

In [58]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [62]:
titanic_sorted = titanic_df.sort_values(by=['Name','Age'],ascending=False,inplace =False)
titanic_sorted.head(10)

PassengerId  Survived  Pclass  \
868          869         0       3   
153          154         0       3   
361          362         0       2   
282          283         0       3   
286          287         1       3   
559          560         1       3   
422          423         0       3   
240          241         0       3   
111          112         0       3   
199          200         0       2   

                                             Name     Sex   Age  SibSp  Parch  \
868                   van Melkebeke, Mr. Philemon    male   NaN      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
361                     del Carlo, Mr. Sebastiano    male  29.0      1      0   
282                     de Pelsmaeker, Mr. Alfons    male  16.0      0      0   
286                       de Mulder, Mr. Theodore    male  30.0      0      0   
559  de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.0      1      0   
422                            Zimmerman, Mr. Leo    male  29.0      0      0   
240                         Zabour, Miss. Thamine  female   NaN      1      0   
111                          Zabour, Miss. Hileni  female  14.5      1      0   
199        Yrois, Miss. Henriette ("Mrs Harbeck")  female  24.0      0      0   

            Ticket     Fare Cabin Embarked  
868         345777   9.5000   NaN        S  
153       A/5. 851  14.5000   NaN        S  
361  SC/PARIS 2167  27.7208   NaN        C  
282         345778   9.5000   NaN        S  
286         345774   9.5000   NaN        S  
559         345572  17.4000   NaN        S  
422         315082   7.8750   NaN        S  
240           2665  14.4542   NaN        C  
111           2665  14.4542   NaN        C  
199         248747  13.0000   NaN        S

In [66]:
titanic_groupby = titanic_df.groupby(by='Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [77]:
titanic_df.groupby('Embarked')['Age'].agg(['mean','count'])

mean  count
Embarked                  
C         30.814769    130
Q         28.089286     28
S         29.445397    554

In [16]:
titanic_df.groupby('Pclass')['Age'].agg(['mean','min','sum','max'])

mean   min      sum   max
Pclass                                
1       38.233441  0.92  7111.42  80.0
2       29.877630  0.67  5168.83  70.0
3       25.140620  0.42  8924.92  74.0

In [83]:
#중요
agg_format = {'Age':'mean','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                             
1       38.233441     90  84.154687
2       29.877630     74  20.662183
3       25.140620    302  13.675550

In [92]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64

In [18]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')

In [85]:
titanic_df['Cabin'].isna().sum()

687

In [91]:
titanic_df['Cabin'].fillna('C000',inplace=True)
titanic_df['Cabin'].isna().sum()

0

In [25]:
lambda_square = lambda x : x**2
print(lambda_square(3))

9


In [97]:
a = [1,2,3]
ss = map(lambda x: x**2,a)
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']]

Name  Name_len
0                              Braund, Mr. Owen Harris        23
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                               Heikkinen, Miss. Laina        22
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        44
4                             Allen, Mr. William Henry        24
..                                                 ...       ...
886                              Montvila, Rev. Juozas        21
887                       Graham, Miss. Margaret Edith        28
888           Johnston, Miss. Catherine Helen "Carrie"        40
889                              Behr, Mr. Karl Howell        21
890                                Dooley, Mr. Patrick        19

[891 rows x 2 columns]

In [38]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [39]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

Age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult
3  35.0       Adult
4  35.0       Adult
5   NaN       Adult
6  54.0       Adult
7   2.0       Child

In [40]:
import sklearn
print(sklearn.__version__)

0.24.2
